sudo: required
services: 
  - docker

  before_install:
    - docker build -t johndraper/docker-react -f Dockerfile.dev .
    
    script:
      - docker run johndraper/docker-react npm run test -- --coverage