language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t johndraper/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true johndraper/docker-react npm run test -- -- coverage